<?php
defined("BASEPATH") or exit("No direct script access allowed");
$Tconfig['base_url'] = 'http://127.0.0.1/';
$Tconfig['sendSMS'] = true;
$Tconfig['enableLog'] = true;
$Tconfig['accessKeyId'] = '';
$Tconfig['accessKeySecret'] = '';
$Tconfig['aliyun_smssign'] = '泉五换届';
$Tconfig['aliyun_smsid_reg'] = '';
$Tconfig['aliyun_smsid_ticket'] = '';
$Tconfig['db_ip'] = 'localhost';
$Tconfig['db_name'] = '';
$Tconfig['db_user'] = 'root';
$Tconfig['db_password'] = '';
$Tconfig['smtp_host'] = 'smtpdm.aliyun.com';
$Tconfig['smtp_port'] = '465';
$Tconfig['smtp_user'] = 'no-reply@mail.2019.qz5z.ren';
$Tconfig['smtp_password'] = '456';
$Tconfig['smtp_crypto'] = 'ssl';
$Tconfig['recaptcha_sitekey'] = '';
$Tconfig['recaptcha_secret'] = '';
$Tconfig['qz5z_secret'] = '';
$Tconfig['qz5z_clientid'] = '';
